server:
  port: 8080
  error:
    include-message: always

spring:
  boot:
    admin:
      client:
        enabled: true
        instance:
          service-url: http://microservice-dialog:8080

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:database-microservice-dialog-changelog.xml
    default_schema: dialog

  datasource:
    url: jdbc:${DATABASE_URL:postgresql://localhost:5432/skillbox}
    username: ${USER_DB:microservice-dialog}
    password: ${PASS_DB:microservice-dialog}
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        default_schema: dialog
    open-in-view: false
