server:
  port: 8080

spring:
  boot:
    admin:
      client:
        enabled: true
        instance:
          service-url: http://microservice-microservice-dialog:8080

  liquibase:
    enabled: false
    drop-first: false
    change-log: classpath:database-microservice-dialog-changelog.xml

  datasource:
    url: jdbc:postgresql://postgres:5432/skillbox
    username: microservice-dialog
    password: microservice-dialog
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        default_schema: microservice-dialog
    open-in-view: false
