apiVersion: v1
kind: ConfigMap
metadata:
  name: microservice-microservice-dialog
data:
  application.yml: |-

    spring:
      boot:
        admin:
          client:
            enabled: true
            instance:
              service-url: http://microservice-microservice-dialog:8080

      liquibase:
        enabled: false
        drop-first: false
        change-log: classpath:database-microservice-dialog-changelog.xml

      datasource:
        url: jdbc:postgresql://postgres:5432/social
        username: ${DATASOURCE_USERNAME}
        password: ${DATASOURCE_PASSWORD}
        driverClassName: org.postgresql.Driver
        hikari:
          minimum-idle: 10
          maximum-pool-size: 50

      jpa:
        show-sql: true
        hibernate:
          ddl-auto: none
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQL10Dialect
            format_sql: true
            default_schema: microservice-dialog
        open-in-view: false

